### ISSUE TITLE
Update log.txt output location

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/NetFixClient#1]
When debugging Outpost 2 multiplayer missions, a log.txt file can be created in the level project folder, rather than the usual place in the game folder. This is caused by running Outpost 2 with the current working directory set to the level project folder, rather than the usual location of the executable's path.

It may make sense to write the log to the same folder as the executable file. That's where the ini resides, along with the saved game files.

Ideally, for new games, on newer versions of Windows, output would go to a user specific folder. I don't think we need to worry about this though, as Outpost 2 is an old game that already doesn't follow the new convention, and newer versions of Windows have compatibility layers to transparently redirect output from older software to user specific folders.

**Comment by Brett208** [comment]
We can use the exported GetGameDir function on op2ext to force the log file to build in same directory as Outpost2.exe. I think this would achieve what you are describing. This would work fine for me as I typically stuff Outpost 2 in the My Documents area or on my desktop.

When I place Outpost 2 in C:/Programs Files (x86), NetFix will not create a log file from scratch. 

Also, when changing settings such as music muted or unit shadows in the game preferences section, the .ini file is not updated. However, I noticed these changes persisted between uses of Outpost 2, so there may be a special way Windows handles .ini files in Program Files. 

So it looks like from the protected folder, Windows is doing something behind the hood to support the .ini file. Perhaps the log file is being created somewhere, but I'm not sure where that would be?

If we want to just flat out not support placing Outpost 2 in program files, then what is proposed in this issue should be fine. It works well for me, but maybe there are other users who would want to put it in Program Files? Maybe I can do some reading later on the issue to see if Windows is stuffing a different copy of the .ini file and log somewhere.

-Brett

**Comment by DanRStevens** [comment]
Using `GetGameDir` sounds like a good plan.

When installed to `Program Files`, and being run without admin privileges, the writes may be silently remapped to "C:\Users\username\AppData\Local\VirtualStore\Program Files\appname\".

_The Old New Thing_ blog has a quick intro explaining how [writes to `Program Files` disappear](https://blogs.msdn.microsoft.com/oldnewthing/20150902-00/?p=91681). The feature is known as [UAC Virtualization](https://docs.microsoft.com/en-us/previous-versions/technet-magazine/cc138019(v=msdn.10)).

I think it's fine if we rely on this feature. Outpost 2 does predate Vista after all.

**Comment by Brett208** [comment]
Just checked, and indeed the .ini and log file are stored in the directory you mentioned with the changes. Thanks for doing the research on this. We should probably mention this somewhere in the op2ext or NetFix documentation. Probably eventually get it into the main game documentation somewhere as well once we get something more significant added for logging.

-Brett

**Comment by DanRStevens** [comment]
Indeed. This would affect saved game files too.

**Comment by DanRStevens** [comment]
I was just thinking, we may now be in a position to update the logging to use the new op2ext logging functionality.
