### ISSUE TITLE
Represent PeerInfo::status as a unscoped enum

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/NetFixClient#103]
It looks like elsewhere in the code status is represented by a short, so maybe PeerInfo's status should be a short.

For example:

```C++
struct StatusUpdate : public TransportLayerHeader
{
	short newStatus;
};

struct NetPeerInfo
{
	int ip;
	short port;
	short status;
	int playerNetID;
};
```

I've seen status be set from 0 to 4, although I haven't located a definitive definition of what each index means. Below are my quick guesses based on OPUNetTransportLayer inspection:

```C++
short enum JoinStatus
{
    0 cleared state?
    1 JoinAttempt or partiallyJoined?
    2 joinSuccess?
    3 Some sort of post join success?
    4 failure state?
}
```

**Comment by Brett208** [comment]
I think the definition is contained in DataStructure Network as:
```
2	 status
0 = EmptySlot
1 = JoiningPlayer [Cleaned from List]
2 = Normal [Initialized value]
3 = Replicated Players List Successfully
4 = Failed to Replicate Players List
```

**Comment by DanRStevens** [comment]
I believe you want [`enum class`](https://en.cppreference.com/w/cpp/language/enum) for this:
```cpp
enum class Status : short { ... }
```

Or maybe even `unsigned short`.

The DataStructure Network comments sound about right. I remember being a little uncertain what those status values meant for a really long time. They were only really known from context, which didn't quite make the meaning immediately clear.

**Comment by Brett208** [comment]
I am a bit worried transferring between status in PeerInfo and the established locations in OP2Internal will be burdensome since they are just a short and not a scoped enum. Using the unscoped enum tends to ease the transfer without needing as many explicit casts. I can give the scoped enum a shot first though.

**Comment by DanRStevens** [comment]
Ahh. Maybe the correct solution would be to add the scoped enum to the OP2Internal project then?
