### ISSUE TITLE
Resolve c-style string deprecation

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/NetFixClient#17]
The following warnings are issued for c-style string manipulation. Not sure if we want to switch to std::string, use new functions, or ignore the warnings.

Warning	C4996	'strncat': This function or variable may be unsafe. Consider using strncat_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	NetFixClient	\netfixclient\opunetgameselectwnd.cpp	648	

Warning	C4996	'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	NetFixClient	\netfixclient\opunettransportlayer.cpp	175	

Warning	C4996	'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	NetFixClient	\netfixclient\main.cpp	58	

Warning	C4996	'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	NetFixClient	\netfixclient\opunettransportlayer.cpp	174	

Warning	C4996	'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	NetFixClient	\netfixclient\opunettransportlayer.cpp	305	

Warning	C4996	'_snprintf': This function or variable may be unsafe. Consider using _snprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	NetFixClient	\netfixclient\opunetgameselectwnd.cpp	639

**Comment by DanRStevens** [comment]
I suppose we probably want to update to use `std::string` where possible. The code base for this project uses some pretty antiquated style.
