### ISSUE TITLE
Standardize filename & file metadata relationship for version control

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/NetFixClient#32]
Past versions of NetFix client would list the version number in the dll file name. Like NetFixV3.dll.

I'd like to standardize to just calling it NetFixClient.dll and adding a version_info resource that contains that actual version number.

This allows us to not have to change the Outpost2.ini file when changing the DLL version. It also slightly simplifies the project settings to not have to update the output filename. Also, if someone changes the filename, it is easy to go in and see which version it actually is (of course that can be defeated with ResourceHacker, but casual renaming doesn't obscure the actual version number)

More importantly to me saying NetFixClient better indicates there is a server somewhere. When I first saw NetFix/NetFixV3.dll, I had no idea a server was involved.

Do we just want to target the next release as V4.0.0?

While I prefer the above plan, not a big deal if others want to stick to the older naming conventions. I'll update the project settings to facilitate either way.

-Brett

**Comment by DanRStevens** [comment]
I'm no fan of the current version format in the filename. Feel free to try out a version resource.

I suppose in the Linux world, it's common to have semantic version numbers on library or executable names, or the folders that contain them. That makes it easy to have multiple versions installed side by side. I don't think we need that here though. In terms of releases, everyone should be using the same version. Using semantic version numbers in the filename would mostly be useful for testing, and I think we can manage without them.

No strong preference on the next version number. I suppose we haven't really made any incompatible changes yet, so if we're using semantic versioning, 3.0.1 is probably the most appropriate.

I don't mind the name NetFixClient. That does imply the existence of a server. However, I should point out NetFix doesn't need a server, and naming something as Client can kind of imply that it's useless without the server.

**Comment by Brett208** [comment]
I'll setup as described in here and push to 3.0.1. We can revisit the actual version number closer to actual release.
