### ISSUE TITLE
Determine Where op2ext::Log should be called

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/NetFixClient#50]
I'm thinking we want to funnel all logged code through logger.h/.cpp within NetFixClient. From there, it can pass the data into op2ext::Log(). I think a better separation of concerns.

Wanted to make sure that was path forward before starting to work that way.

**Comment by DanRStevens** [comment]
I think that works well. From a maintainability standpoint it may be best to collect all references to an external library into just a few places. That makes it easier to update if their are any change in the dependency, such as a method rename, or a breaking API change.
