### ISSUE TITLE
Create a FormatPlayerNetID subroutine

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/NetFixClient#56]
Create a helper routine that standardizes formatting PlayerNetID.

Consider code below as starting point:

https://github.com/OutpostUniverse/NetFixClient/blob/ff9e634120dfb3ce04e126d9d2470096557743d2/OPUNetTransportLayer.cpp#L1125-L1126

https://github.com/OutpostUniverse/NetFixClient/blob/ff9e634120dfb3ce04e126d9d2470096557743d2/OPUNetTransportLayer.cpp#L1406-L1411

**Comment by DanRStevens** [comment]
I should point out we already have a `FormatPlayerNetID` method:
https://github.com/OutpostUniverse/NetFixClient/blob/ff9e634120dfb3ce04e126d9d2470096557743d2/Log.cpp#L57-L64

We just need to start using it.
